### ISSUE TITLE
Can't open file dialog on Mac OS X 10.9.2 for "PoissonCloningInteractive"

### ISSUE THREAD

**Issue by panovr** [daviddoria/InteractivePoissonEditing#1]
Running "PoissonCloningInteractive" on Mac OS X 10.9.2, and selecting "File->Open Images" menu command.
However, the open file dialog can't be displayed.
The output message is:
PoissonCloningGUI
Not using filename arguments.
QMetaObject::connectSlotsByName: No matching signal for on_actionOpenImages_activated()
QMetaObject::connectSlotsByName: No matching signal for on_actionSaveResult_activated()

**Comment by daviddoria** [comment]
Which version of Qt are you using? It works fine for me on Linux with Qt 4.8.4. I looked online a little bit for this problem on Mac and it sounds like it might have been a Qt bug that was resolved in later versions. Can you try a little bit later Qt version?

**Comment by panovr** [comment]
I installed Qt 4.8.6 by homebrew.

**Comment by panovr** [comment]
commit aea399d9218038652168385ed405f5e23857b7d8
commit 2567fa0e0fc097de8b93baf6f19dca66d4f08187

solved this issue.
